routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('/',['as'=>"home",'uses'=>'ViewController@home']);

    Route::resource('categories','CategoryController');

    Route::resource('headings','HeadingController');
   
    Route::resource('users','UserController');

    Route::resource('services','ServiceController');

    Route::resource('packages','PackageController');

    Route::resource('offers','OfferController');

    Route::resource("sliders",'SliderController');

    Route::get('users/wallet/{user_id}',['as'=>'users.wallet','uses'=>'UserController@wallet']);

    Route::get('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@services']);

    Route::get('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@services']);

    Route::post('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@addService']);

    Route::post('users/wallet/{user_id}',['as'=>'users.wallet','uses'=>'UserController@walletAdd']);

    Route::any('users/ban/{id}/{status}',['as'=>'users.ban','uses'=>'UserController@ban']);

    Route::get('users/subscriptions/{user_id}',['as'=>'users.subscriptions','uses'=>'UserController@subscriptions']);

    Route::post('users/subscriptions/{user_id}',['as'=>'users.subscriptions','uses'=>'UserController@addSubscription']);

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('change/password',['as'=>'changePassword','uses'=>'LoginController@showChangePassword']);

    Route::post('change/password',['as'=>'changePassword','uses'=>'LoginController@changePassword']);

    Route::get('franchise',['as'=>'franchise','uses'=>'ViewController@franchise']);

    Route::get('contact/us',['as'=>'contactUs','uses'=>'ViewController@contactUs']);

    Route::get('feedbacks',['as'=>'feedback','uses'=>'ViewController@feedback']);

    Route::get('career',['as'=>'career','uses'=>'ViewController@career']);

    Route::delete('delete/{table}/{id}',['as'=>'table.destroy','uses'=>'AjaxController@tableDestroy']);

    Route::get('salon/parties',['as'=>'salonParties','uses'=>'ViewController@party']);

    Route::get('home/services',['as'=>'homeServices','uses'=>'ViewController@homeServices']);

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::any('get/categories/{parent_id?}',['as'=>'getCategories','uses'=>'AjaxController@getCategories']);

        Route::any('get/headings/{category_id?}',['as'=>'getHeadings','uses'=>'AjaxController@getHeadings']);
        
        Route::any('get/services/{category_id?}',['as'=>'getServices','uses'=>'AjaxController@getServices']);

        Route::any('packages/{category_id?}',['as'=>'packages','uses'=>'AjaxController@packages']);

    });
    
    
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return redirect()->route('admin.home');
});

Route::get('logout',['as'=>'logout','uses'=>'Admin\LoginController@logout']);

app/Heading.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Heading extends Model
{
    //
    protected $fillable = [
        'title',
        'category_id'
    ];

    public function services(){
        return $this->hasMany('App\Service','heading_id','id')
             ->whereType('service')
             ->select(
                 'id',
                 'heading_id',
                 'category_id',
                 'title',
                //  'description',
                //  'image',
                 'duration',
                 'price',
                 'sale_price'
             )
             ;
     }
}

app/Http/Controllers/Admin/HeadingController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Heading;
use Illuminate\Http\Request;
use App\Category;
use App\DataTables\CategoriesDataTable;
use Illuminate\Support\Arr;
use \Validator;



class HeadingController extends Controller
{
    protected $attributes = [
        'category_id',
        'title'
    ];

    protected $validationRules =[
        'category_id'=>'required|exists:categories,id',
        'title'=>'required|max:300'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Heading::leftJoin('categories','categories.id','=','headings.category_id')
                        ->leftJoin('categories as genders','genders.id','=','categories.parent_id')
                            ->select(
                                'categories.title as category',
                                'genders.title as gender',
                                'headings.*'
                            )->get();
                            // return $data;
        return view('admin.headings.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::whereNull('parent_id')->get();
        return view('admin.headings.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;
       
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());
        
       
        
       if(Heading::create($input)){
           flash()->ok('Heading Created Successfully !');
           return redirect()->route('admin.headings.index');
       }

       flash()->err();
       return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $Data = Heading::leftJoin('categories','categories.id','=','headings.category_id')
                            ->select(
                                'categories.parent_id',
                                'headings.*'
                            )
                            ->where('headings.id',$id)
                            ->first();
        if(!$Data){
            return abort(404);
        }
        // return $Data;
        $categories = Category::whereNull('parent_id')->get();
        return view('admin.headings.edit',compact('Data','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update($id,Request $req)
    {
        //
        $Heading = Heading::findOrFail($id);
        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;
      
      
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());
        
       

       if($Heading->update($input)){
           flash()->ok('Heading Updated Successfully !');
           return redirect()->route('admin.headings.index');
       }

       flash()->err();
       return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // return api()->success(['data'=>Category::findOrFail($id)->delete()]);
        if(Heading::findOrFail($id)->delete())
            return api()->success(['message'=>"Heading deleted successfully !"]);

        return api()->error();
        // return $id;
    }
}

resources/views/admin/headings/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('categories.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('categories.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/admin/headings/create.blade.php
@extends('admin.layouts.default')
@section('title','Create ')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Create </h6> <a href="{{route('admin.headings.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to List</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('admin.headings.store')}}" enctype="multipart/form-data">
                @include('admin.headings.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create </button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/admin/headings/edit.blade.php
@extends('admin.layouts.default')
@section('title','Edit')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit </h6> <a href="{{route('admin.headings.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to List</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('admin.headings.update',$Data->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('admin.headings.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update </button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/admin/headings/fields.blade.php
<div class="row">
    {!! csrf_field() !!}

    <div class="col-md-4 col-sm-4 form-group">
        <label>Gender</label>
        <select name="parent_id" previousValue="{{old('parent_id',$Data->parent_id??null)}}" id="" target="[name='category_id']" class="form-control loadDataOnChange">
        <option value="">Select</option>
            @foreach($categories as $category)
                <option {{$category->id==old('parent_id',$Data->parent_id??null)?'selected':''}} value="{{$category->id}}">{{$category->title}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('parent_id')}}
        </p>
    </div>

    <div class="col-md-4 col-sm-4 form-group">
        <label>Category </label>
        <select name="category_id" previousValue="{{old('category_id',$Data->category_id??null)}}" url="{{route('admin.ajax.getCategories')}}" id="" class="form-control">
           
        </select>
        <p class="error">
            {{$errors->first('category_id')}}
        </p>
    </div>
    <div class="col-md-4 col-sm-4 form-group">
        <label>Title</label>
        <input type="text" name="title"  class="form-control" value="{{old('title',$Data->title??'')}}" />
        <p class="error">
            {{$errors->first('title')}}
        </p>
    </div>

    

    

    

   

    
   

  
    
</div>

resources/views/admin/headings/index.blade.php
@extends('admin.layouts.default')
@section('title','headings')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">headings</h6> <a href="{{route('admin.headings.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create </a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <table class="table d_table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Gender</th>
                  <th>Category</th>
                  <th>Heading</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach($data as $d)
                <tr>
                  <td>
                    {{$d->id}}
                  </td>
                  <td>
                    {{$d->gender}}
                  </td>
                 
                  <td>
                    {{$d->category}}
                  </td>
                  <td>
                    {{$d->title}}
                  </td>
              

                  
                  
                  <td>
                    <div class='btn-group btn-group-sm'>
                      <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('admin.headings.edit', $d->id) }}" class='btn btn-link'>
                        <i class="fa fa-edit"></i>
                      </a>
                      <a onclick="trashUtil(this)" trash-url="{{ route('admin.headings.destroy', $d->id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
                        <i class="fa fa-trash"></i>
                      </a>
                    </div>
                    
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

<script>
   
</script>
@endpush