routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('/',['as'=>"home",'uses'=>'ViewController@home']);

    Route::resource('categories','CategoryController');

    Route::resource('headings','HeadingController');
   
    Route::resource('users','UserController');

    Route::resource('services','ServiceController');

    Route::resource('packages','PackageController');

    Route::resource('offers','OfferController');

    Route::resource("sliders",'SliderController');

    Route::get('users/wallet/{user_id}',['as'=>'users.wallet','uses'=>'UserController@wallet']);

    Route::get('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@services']);

    Route::get('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@services']);

    Route::post('users/services/{user_id}',['as'=>'users.services','uses'=>'UserController@addService']);

    Route::post('users/wallet/{user_id}',['as'=>'users.wallet','uses'=>'UserController@walletAdd']);

    Route::any('users/ban/{id}/{status}',['as'=>'users.ban','uses'=>'UserController@ban']);

    Route::get('users/subscriptions/{user_id}',['as'=>'users.subscriptions','uses'=>'UserController@subscriptions']);

    Route::post('users/subscriptions/{user_id}',['as'=>'users.subscriptions','uses'=>'UserController@addSubscription']);

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('change/password',['as'=>'changePassword','uses'=>'LoginController@showChangePassword']);

    Route::post('change/password',['as'=>'changePassword','uses'=>'LoginController@changePassword']);

    Route::get('franchise',['as'=>'franchise','uses'=>'ViewController@franchise']);

    Route::get('contact/us',['as'=>'contactUs','uses'=>'ViewController@contactUs']);

    Route::get('feedbacks',['as'=>'feedback','uses'=>'ViewController@feedback']);

    Route::get('career',['as'=>'career','uses'=>'ViewController@career']);

    Route::delete('delete/{table}/{id}',['as'=>'table.destroy','uses'=>'AjaxController@tableDestroy']);

    Route::get('salon/parties',['as'=>'salonParties','uses'=>'ViewController@party']);

    Route::get('home/services',['as'=>'homeServices','uses'=>'ViewController@homeServices']);

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::any('get/categories/{parent_id?}',['as'=>'getCategories','uses'=>'AjaxController@getCategories']);

        Route::any('get/headings/{category_id?}',['as'=>'getHeadings','uses'=>'AjaxController@getHeadings']);
        
        Route::any('get/services/{category_id?}',['as'=>'getServices','uses'=>'AjaxController@getServices']);

        Route::any('packages/{category_id?}',['as'=>'packages','uses'=>'AjaxController@packages']);

    });
    
    
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return redirect()->route('admin.home');
});

Route::get('logout',['as'=>'logout','uses'=>'Admin\LoginController@logout']);

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Service extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'category_id',
        'title',
        'description',
        'image',
        'duration',
        'price',
        'sale_price',
        'type',
        'heading_id',
    ];
    protected $hidden = ['deleted_at'];

    public function getImageAttribute($v)
    {
        return url($v);
    }

    public function getCategoryIconAttribute($v)
    {
        return url($v);
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Category;
use Illuminate\Http\Request;

use App\DataTables\CategoriesDataTable;
use Illuminate\Support\Arr;
use \Validator;

use App\Service;

class ServiceController extends Controller
{
    protected $attributes = [
        'category_id',
        'title',
        // 'description',
        // 'image',
        'duration',
        'price',
        'sale_price',
        'heading_id',
        
    ];

    protected $validationRules =[
        'category_id'=>'required|exists:categories,id',
        'title'=>'required|max:300',
        // 'description'=>'required|max:500',
        // 'image'=>'required|image|max:2000',
        'duration'=>'required|numeric|min:1',
        'price'=>'required|numeric|min:0|greater_than_field:sale_price',
        'sale_price'=>'required|numeric|min:0',
        'heading_id'=>'required'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Service::join('categories','categories.id','=','services.category_id')
                            ->leftJoin('headings','headings.id','=','services.heading_id')
                            ->select(
                                'services.*',
                                'headings.title as heading',
                                'categories.title as category'
                            )
                            ->whereType('service')

                            ->get();
        return view('admin.services.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::whereNull('parent_id')->get();
        return view('admin.services.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;

        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());
        
        // $input['image'] = upload($req->file('image'),'services/');
        
       if(Service::create($input)){
           flash()->ok('Service Created Successfully !');
           return redirect()->route('admin.services.index');
       }

       flash()->err();
       return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $Data = Service::leftJoin('categories','categories.id','=','services.category_id')
                        ->where('services.id',$id)
                        ->select(
                            'categories.parent_id',
                            'services.*'
                            )
                        ->first();

        if(!$Data){
            return abort(404);
        }
        // return $Data;
        $categories = Category::whereNull('parent_id')->get();
        return view('admin.services.edit',compact('Data','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update($id,Request $req)
    {
        //
        $Service = Service::findOrFail($id);
        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;
        // $rules['image'] = str_replace("required",'nullable',$rules['image']);
        // if($req->hasFile('image')){
        //     $input['image'] = upload($req->file('image'),'services/');
        // }else{
        //     unset($input['image']);
        // }
      
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());
        


       if($Service->update($input)){
           flash()->ok('Service Updated Successfully !');
           return redirect()->route('admin.services.index');
       }

       flash()->err();
       return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // return api()->success(['data'=>Category::findOrFail($id)->delete()]);
        if(Service::findOrFail($id)->delete())
            return api()->success(['message'=>"Service deleted successfully !"]);

        return api()->error();
        // return $id;
    }
}

resources/views/admin/services/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('categories.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('categories.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/admin/services/create.blade.php
@extends('admin.layouts.default')
@section('title','Create Service')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Create Service</h6> <a href="{{route('admin.services.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Services</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('admin.services.store')}}" enctype="multipart/form-data">
                @include('admin.services.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create </button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/admin/services/edit.blade.php
@extends('admin.layouts.default')
@section('title','Edit Service')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit Service</h6> <a href="{{route('admin.services.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Services</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('admin.services.update',$Data->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('admin.services.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update </button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/admin/services/fields.blade.php
<div class="row">
    {!! csrf_field() !!}

    <div class="col-md-4 col-sm-4 form-group">
        <label>Parent Category</label>
        <select name="parent_id" id="" previousValue="{{old('parent_id',$Data->parent_id??'')}}" class="form-control loadDataOnChange" target="[name='category_id']">
            <option value="">Select</option>
            @foreach($categories as $category)
                <option {{$category->id==old('parent_id',$Data->parent_id??null)?'selected':''}} value="{{$category->id}}">{{$category->title}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('parent_id')}}
        </p>
    </div>
    <div class="col-md-4 col-sm-4 form-group">
        <label>Category</label>
        <select name="category_id" target="[name='heading_id']" url="{{route('admin.ajax.getCategories')}}" previousValue="{{old('category_id',$Data->category_id??'')}}" id="" class="form-control loadDataOnChange">
           
        </select>
        <p class="error">
            {{$errors->first('category_id')}}
        </p>
    </div>

    <div class="col-md-4 col-sm-4 form-group">
        <label>Heading</label>
        <select name="heading_id" previousValue="{{old('heading_id',$Data->heading_id??'')}}" url="{{route('admin.ajax.getHeadings')}}" id="" class="form-control">
           
        </select>
        <p class="error">
            {{$errors->first('heading_id')}}
        </p>
    </div>

    <div class="col-md-12 col-sm-12 form-group">
        <label>Title</label>
        <input type="text" name="title"  class="form-control" value="{{old('title',$Data->title??'')}}" />
        <p class="error">
            {{$errors->first('title')}}
        </p>
    </div>

    {{-- <div class="col-md-12 col-sm-12 form-group">
        <label>Description</label>
        <textarea name="description"  class="form-control">{{old('description',$Data->description??'')}}</textarea>
        <p class="error">
            {{$errors->first('description')}}
        </p>
    </div> --}}

    {{-- <div class="col-md-3 col-sm-3 form-group">
        <label>Image</label>
        <input type="file" name="image"  class="form-control" value="{{old('image',$Data->image??'')}}" />
        <p class="error">
            {{$errors->first('image')}}
        </p>
    </div> --}}

    <div class="col-md-3 col-sm-3 form-group">
        <label>Duration (Mins)</label>
        <input type="number" name="duration"  class="form-control" value="{{old('duration',$Data->duration??'')}}" />
        <p class="error">
            {{$errors->first('duration')}}
        </p>
    </div>  

    <div class="col-md-3 col-sm-3 form-group">
        <label>Price</label>
        <input type="text" name="price"  class="form-control" value="{{old('price',$Data->price??'')}}" />
        <p class="error">
            {{$errors->first('price')}}
        </p>
    </div>  

    <div class="col-md-3 col-sm-3 form-group">
        <label>Sale Price</label>
        <input type="text" name="sale_price"  class="form-control" value="{{old('sale_price',$Data->sale_price??'')}}" />
        <p class="error">
            {{$errors->first('sale_price')}}
        </p>
    </div>  

  
    
</div>

resources/views/admin/services/index.blade.php
@extends('admin.layouts.default')
@section('title','services')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Services</h6> <a href="{{route('admin.services.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create </a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <table class="table d_table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Category</th>
                  <th>Heading</th>
                  
                  <th>Name</th>
                  {{-- <th>Image</th> --}}
                  <th>Duration</th>
                  <th>Price</th>
                  <th>Sale Price</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach($data as $d)
                <tr>
                  <td>
                    {{$d->id}}
                  </td>
                  <td>
                    {{$d->category}}
                  </td>
                  <td>
                    {{$d->heading}}
                  </td>
                  <td>
                    {{$d->title}}
                  </td>
                  {{-- <td>
                    <img src="{{$d->image}}" style="max-height:10vh;" alt="">
                  </td> --}}
                  <td>
                    {{$d->duration}}
                  </td>
                  <td>
                    {{$d->price}}
                  </td>

                  <td>
                    {{$d->sale_price}}
                  </td>

                  
                  
                  <td>
                    <div class='btn-group btn-group-sm'>
                      <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('admin.services.edit', $d->id) }}" class='btn btn-link'>
                        <i class="fa fa-edit"></i>
                      </a>
                      <a onclick="trashUtil(this)" trash-url="{{ route('admin.services.destroy', $d->id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
                        <i class="fa fa-trash"></i>
                      </a>
                    </div>
                    
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

<script>
   
</script>
@endpush